In [1]:
import sqlite3
import csv
from Hopper import *

In [2]:
verbose = True
h = dbms(verbose=verbose)

DROP TABLE IF EXISTS i_ids;

CREATE TABLE i_ids (
	i_id TEXT NOT NULL,
	PRIMARY KEY (i_id)
);

DROP TABLE IF EXISTS i_windows;

CREATE TABLE i_windows (
	i_id TEXT NOT NULL,
	i_st INTEGER NOT NULL,
	i_et INTEGER NOT NULL,
	PRIMARY KEY (i_id),
	FOREIGN KEY (i_id) REFERENCES i_ids (i_id)
);

DROP TABLE IF EXISTS i_partitions;

CREATE TABLE i_partitions (
	i_id TEXT NOT NULL,
	partition TEXT NOT NULL,
	PRIMARY KEY (i_id),
	FOREIGN KEY (i_id) REFERENCES i_ids (i_id)
);

DROP TABLE IF EXISTS i_relcal;

CREATE TABLE i_relcal (
	i_id TEXT NOT NULL,
	i_st INTEGER NOT NULL,
	i_et INTEGER NOT NULL
);

In [3]:
tc = table_config("characteristics_0", 
                  ["age", "sex", "eth", "bin_ldc", "job"], 
                  ["real", "bin", "ldc", "ldc", "hdc"],
                  has_times=False,
                  primary_key=True)
h.create_fvm_with_csv(tc, "data/characteristics_0.csv", delimiter=',')


_tc = table_config("samples_0", 
                  ["SBP", "DBP", "type"], 
                  ["real", "real", "ldc"], 
                  has_times=True,
                  primary_key=False)
h.create_fvm_with_csv(_tc, "data/samples_0.csv", delimiter=',')

_tc = table_config("samples_1", 
                  ["tmps", "hrs", "sbps", "rrs", "dbps", "sats", "wgts"],
                  ["real", "real", 'real', "real", "real", "real", "real"], 
                  has_times=True,
                  primary_key=False)
h.create_fvm_with_csv(_tc, "data/samples_1.csv", delimiter=',')


_tc = table_config("samples_2", 
                  ["dx"],
                  ["hdc"], 
                  has_times=True,
                  primary_key=False)
h.create_fvm_with_csv(_tc, "data/samples_2.csv", delimiter=',')


_tc = table_config("samples_3", 
                  ["outcome"],
                  ["bin"], 
                  has_times=True,
                  primary_key=False)
h.create_fvm_with_csv(_tc, "data/samples_3.csv", delimiter=',')

DROP TABLE IF EXISTS characteristics_0;

CREATE TABLE characteristics_0 (
	i_id TEXT NOT NULL,
	age REAL NOT NULL,
	sex TEXT NOT NULL,
	eth TEXT NOT NULL,
	bin_ldc TEXT NOT NULL,
	job TEXT NOT NULL,
	PRIMARY KEY (i_id),
	FOREIGN KEY (i_id) REFERENCES i_ids (i_id)
);

INSERT OR IGNORE INTO i_ids (i_id) VALUES (?);

INSERT  INTO characteristics_0 (i_id, age, sex, eth, bin_ldc, job) VALUES (?, ?, ?, ?, ?, ?);

CREATE INDEX i_index_characteristics_0_i_id ON characteristics_0(i_id);

CREATE INDEX i_index_characteristics_0_age ON characteristics_0(age);

CREATE INDEX i_index_characteristics_0_sex ON characteristics_0(sex);

CREATE INDEX i_index_characteristics_0_eth ON characteristics_0(eth);

CREATE INDEX i_index_characteristics_0_bin_ldc ON characteristics_0(bin_ldc);

CREATE INDEX i_index_characteristics_0_job ON characteristics_0(job);

10000 rows loaded

DROP TABLE IF EXISTS samples_0;

CREATE TABLE samples_0 (
	i_id TEXT NOT NULL,
	i_st INTEGER NOT NULL,
	i_et INTEGER NOT NULL,
	SBP REAL NOT NULL,
	DBP REAL NOT NULL,
	type TEXT NOT NULL,
	FOREIGN KEY (i_id) REFERENCES i_ids (i_id)
);

INSERT OR IGNORE INTO i_ids (i_id) VALUES (?);

INSERT  INTO samples_0 (i_id, i_st, i_et, SBP, DBP, type) VALUES (?, ?, ?, ?, ?, ?);

CREATE INDEX i_index_samples_0_i_id ON samples_0(i_id);

CREATE INDEX i_index_samples_0_i_st ON samples_0(i_st);

CREATE INDEX i_index_samples_0_i_et ON samples_0(i_et);

CREATE INDEX i_index_samples_0_SBP ON samples_0(SBP);

CREATE INDEX i_index_samples_0_DBP ON samples_0(DBP);

CREATE INDEX i_index_samples_0_type ON samples_0(type);

200000 rows loaded

DROP TABLE IF EXISTS samples_1;

CREATE TABLE samples_1 (
	i_id TEXT NOT NULL,
	i_st INTEGER NOT NULL,
	i_et INTEGER NOT NULL,
	tmps REAL NOT NULL,
	hrs REAL NOT NULL,
	sbps REAL NOT NULL,
	rrs REAL NOT NULL,
	dbps REAL NOT NULL,
	sats REAL NOT NULL,
	wgts REAL NOT NULL,
	FOREIGN KEY (i_id) REFERENCES i_ids (i_id)
);

INSERT OR IGNORE INTO i_ids (i_id) VALUES (?);

INSERT  INTO samples_1 (i_id, i_st, i_et, tmps, hrs, sbps, rrs, dbps, sats, wgts) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);

CREATE INDEX i_index_samples_1_i_id ON samples_1(i_id);

CREATE INDEX i_index_samples_1_i_st ON samples_1(i_st);

CREATE INDEX i_index_samples_1_i_et ON samples_1(i_et);

CREATE INDEX i_index_samples_1_tmps ON samples_1(tmps);

CREATE INDEX i_index_samples_1_hrs ON samples_1(hrs);

CREATE INDEX i_index_samples_1_sbps ON samples_1(sbps);

CREATE INDEX i_index_samples_1_rrs ON samples_1(rrs);

CREATE INDEX i_index_samples_1_dbps ON samples_1(dbps);

CREATE INDEX i_index_samples_1_sats ON samples_1(sats);

CREATE INDEX i_index_samples_1_wgts ON samples_1(wgts);

200000 rows loaded

DROP TABLE IF EXISTS samples_2;

CREATE TABLE samples_2 (
	i_id TEXT NOT NULL,
	i_st INTEGER NOT NULL,
	i_et INTEGER NOT NULL,
	dx TEXT NOT NULL,
	FOREIGN KEY (i_id) REFERENCES i_ids (i_id)
);

INSERT OR IGNORE INTO i_ids (i_id) VALUES (?);

INSERT  INTO samples_2 (i_id, i_st, i_et, dx) VALUES (?, ?, ?, ?);

CREATE INDEX i_index_samples_2_i_id ON samples_2(i_id);

CREATE INDEX i_index_samples_2_i_st ON samples_2(i_st);

CREATE INDEX i_index_samples_2_i_et ON samples_2(i_et);

CREATE INDEX i_index_samples_2_dx ON samples_2(dx);

200000 rows loaded

DROP TABLE IF EXISTS samples_3;

CREATE TABLE samples_3 (
	i_id TEXT NOT NULL,
	i_st INTEGER NOT NULL,
	i_et INTEGER NOT NULL,
	outcome TEXT NOT NULL,
	FOREIGN KEY (i_id) REFERENCES i_ids (i_id)
);

INSERT OR IGNORE INTO i_ids (i_id) VALUES (?);

INSERT  INTO samples_3 (i_id, i_st, i_et, outcome) VALUES (?, ?, ?, ?);

CREATE INDEX i_index_samples_3_i_id ON samples_3(i_id);

CREATE INDEX i_index_samples_3_i_st ON samples_3(i_st);

CREATE INDEX i_index_samples_3_i_et ON samples_3(i_et);

CREATE INDEX i_index_samples_3_outcome ON samples_3(outcome);

10000 rows loaded

In [4]:
#h.dew_it()

In [5]:
h.set_windows([['00000', 2, 5], ['00001', 3, 7]],)

INSERT  INTO i_windows (i_id, i_st, i_et) VALUES (?, ?, ?);

INSERT OR IGNORE INTO i_windows
SELECT * FROM (
	SELECT i_id, MIN(i_st) AS i_st, MAX(i_et) AS i_et
	FROM (
	    SELECT i_id, i_st, i_et
		FROM samples_0
		UNION
			SELECT i_id, i_st, i_et
		FROM samples_1
		UNION
			SELECT i_id, i_st, i_et
		FROM samples_2
		UNION
			SELECT i_id, i_st, i_et
		FROM samples_3

	)
	GROUP BY i_id
);

In [6]:
h.set_partitions([['00000', 'dev'], ['00001', 'dev']])

INSERT  INTO i_partitions (i_id, partition) VALUES (?, ?);

INSERT OR IGNORE INTO i_partitions
SELECT * FROM (
	SELECT i_id, CASE
		 WHEN r <= 0.8 THEN "train"
		 WHEN r <= 0.9 THEN "dev"
		 WHEN r <= 1.0 THEN "test"
		 ELSE "test"
	END
	FROM (SELECT i_id, ABS(RANDOM())/(9223372036854775807.0) AS r FROM i_ids)
);

In [7]:
h.create_windows_views()

CREATE VIEW win_samples_0 AS
    SELECT samples_0.i_id,
	MAX(samples_0.i_st, i_windows.i_st) AS i_st,
	MIN(samples_0.i_et, i_windows.i_et) AS i_et,
	SBP,
	DBP,
	type
	FROM (
	    samples_0 JOIN i_windows ON samples_0.i_id=i_windows.i_id
	)
	WHERE NOT (i_windows.i_et < samples_0.i_st OR
	           i_windows.i_st > samples_0.i_et)

;

CREATE VIEW win_samples_1 AS
    SELECT samples_1.i_id,
	MAX(samples_1.i_st, i_windows.i_st) AS i_st,
	MIN(samples_1.i_et, i_windows.i_et) AS i_et,
	tmps,
	hrs,
	sbps,
	rrs,
	dbps,
	sats,
	wgts
	FROM (
	    samples_1 JOIN i_windows ON samples_1.i_id=i_windows.i_id
	)
	WHERE NOT (i_windows.i_et < samples_1.i_st OR
	           i_windows.i_st > samples_1.i_et)

;

CREATE VIEW win_samples_2 AS
    SELECT samples_2.i_id,
	MAX(samples_2.i_st, i_windows.i_st) AS i_st,
	MIN(samples_2.i_et, i_windows.i_et) AS i_et,
	dx
	FROM (
	    samples_2 JOIN i_windows ON samples_2.i_id=i_windows.i_id
	)
	WHERE NOT (i_windows.i_et < samples_2.i_st OR
	           i_windows.i_st > samples_2.i_et)

;

CREATE VIEW win_samples_3 AS
    SELECT samples_3.i_id,
	MAX(samples_3.i_st, i_windows.i_st) AS i_st,
	MIN(samples_3.i_et, i_windows.i_et) AS i_et,
	outcome
	FROM (
	    samples_3 JOIN i_windows ON samples_3.i_id=i_windows.i_id
	)
	WHERE NOT (i_windows.i_et < samples_3.i_st OR
	           i_windows.i_st > samples_3.i_et)

;

In [8]:
h.create_partition_views_prior_to_filter()

SELECT DISTINCT(partition) FROM i_partitions;

partitions: dev,train,test

CREATE VIEW i_partitions_dev_org_characteristics_0 AS
    SELECT * FROM characteristics_0
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='dev'
	)

;

CREATE VIEW i_partitions_train_org_characteristics_0 AS
    SELECT * FROM characteristics_0
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='train'
	)

;

CREATE VIEW i_partitions_test_org_characteristics_0 AS
    SELECT * FROM characteristics_0
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='test'
	)

;

CREATE VIEW i_partitions_dev_win_samples_0 AS
    SELECT * FROM win_samples_0
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='dev'
	)

;

CREATE VIEW i_partitions_train_win_samples_0 AS
    SELECT * FROM win_samples_0
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='train'
	)

;

CREATE VIEW i_partitions_test_win_samples_0 AS
    SELECT * FROM win_samples_0
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='test'
	)

;

CREATE VIEW i_partitions_dev_win_samples_1 AS
    SELECT * FROM win_samples_1
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='dev'
	)

;

CREATE VIEW i_partitions_train_win_samples_1 AS
    SELECT * FROM win_samples_1
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='train'
	)

;

CREATE VIEW i_partitions_test_win_samples_1 AS
    SELECT * FROM win_samples_1
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='test'
	)

;

CREATE VIEW i_partitions_dev_win_samples_2 AS
    SELECT * FROM win_samples_2
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='dev'
	)

;

CREATE VIEW i_partitions_train_win_samples_2 AS
    SELECT * FROM win_samples_2
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='train'
	)

;

CREATE VIEW i_partitions_test_win_samples_2 AS
    SELECT * FROM win_samples_2
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='test'
	)

;

CREATE VIEW i_partitions_dev_win_samples_3 AS
    SELECT * FROM win_samples_3
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='dev'
	)

;

CREATE VIEW i_partitions_train_win_samples_3 AS
    SELECT * FROM win_samples_3
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='train'
	)

;

CREATE VIEW i_partitions_test_win_samples_3 AS
    SELECT * FROM win_samples_3
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='test'
	)

;

In [9]:
h.fit_filter(partition='train', percentile_cutoff=0.05)

SELECT COUNT(*) FROM i_partitions_train_org_characteristics_0;

SELECT AVG(age) AS avg,
       SUM((age-(SELECT AVG(age) FROM i_partitions_train_org_characteristics_0))*
       (age-(SELECT AVG(age) FROM i_partitions_train_org_characteristics_0)))
       /(COUNT(age)-1) AS var
FROM i_partitions_train_org_characteristics_0
;

SELECT sex, COUNT(*) AS n
FROM i_partitions_train_org_characteristics_0
GROUP BY sex
ORDER BY n DESC
;


SELECT eth, COUNT(*) AS n
FROM i_partitions_train_org_characteristics_0
GROUP BY eth
ORDER BY n DESC
;


SELECT bin_ldc, COUNT(*) AS n
FROM i_partitions_train_org_characteristics_0
GROUP BY bin_ldc
ORDER BY n DESC
;


SELECT job, COUNT(*) AS n
FROM i_partitions_train_org_characteristics_0
GROUP BY job
ORDER BY n DESC
;


SELECT COUNT(*) FROM i_partitions_train_win_samples_0;

SELECT AVG(SBP) AS avg,
       SUM((SBP-(SELECT AVG(SBP) FROM i_partitions_train_win_samples_0))*
       (SBP-(SELECT AVG(SBP) FROM i_partitions_train_win_samples_0)))
       /(COUNT(SBP)-1) AS var
FROM i_partitions_train_win_samples_0
;

SELECT AVG(DBP) AS avg,
       SUM((DBP-(SELECT AVG(DBP) FROM i_partitions_train_win_samples_0))*
       (DBP-(SELECT AVG(DBP) FROM i_partitions_train_win_samples_0)))
       /(COUNT(DBP)-1) AS var
FROM i_partitions_train_win_samples_0
;

SELECT type, COUNT(*) AS n
FROM i_partitions_train_win_samples_0
GROUP BY type
ORDER BY n DESC
;


SELECT COUNT(*) FROM i_partitions_train_win_samples_1;

SELECT AVG(tmps) AS avg,
       SUM((tmps-(SELECT AVG(tmps) FROM i_partitions_train_win_samples_1))*
       (tmps-(SELECT AVG(tmps) FROM i_partitions_train_win_samples_1)))
       /(COUNT(tmps)-1) AS var
FROM i_partitions_train_win_samples_1
;

SELECT AVG(hrs) AS avg,
       SUM((hrs-(SELECT AVG(hrs) FROM i_partitions_train_win_samples_1))*
       (hrs-(SELECT AVG(hrs) FROM i_partitions_train_win_samples_1)))
       /(COUNT(hrs)-1) AS var
FROM i_partitions_train_win_samples_1
;

SELECT AVG(sbps) AS avg,
       SUM((sbps-(SELECT AVG(sbps) FROM i_partitions_train_win_samples_1))*
       (sbps-(SELECT AVG(sbps) FROM i_partitions_train_win_samples_1)))
       /(COUNT(sbps)-1) AS var
FROM i_partitions_train_win_samples_1
;

SELECT AVG(rrs) AS avg,
       SUM((rrs-(SELECT AVG(rrs) FROM i_partitions_train_win_samples_1))*
       (rrs-(SELECT AVG(rrs) FROM i_partitions_train_win_samples_1)))
       /(COUNT(rrs)-1) AS var
FROM i_partitions_train_win_samples_1
;

SELECT AVG(dbps) AS avg,
       SUM((dbps-(SELECT AVG(dbps) FROM i_partitions_train_win_samples_1))*
       (dbps-(SELECT AVG(dbps) FROM i_partitions_train_win_samples_1)))
       /(COUNT(dbps)-1) AS var
FROM i_partitions_train_win_samples_1
;

SELECT AVG(sats) AS avg,
       SUM((sats-(SELECT AVG(sats) FROM i_partitions_train_win_samples_1))*
       (sats-(SELECT AVG(sats) FROM i_partitions_train_win_samples_1)))
       /(COUNT(sats)-1) AS var
FROM i_partitions_train_win_samples_1
;

SELECT AVG(wgts) AS avg,
       SUM((wgts-(SELECT AVG(wgts) FROM i_partitions_train_win_samples_1))*
       (wgts-(SELECT AVG(wgts) FROM i_partitions_train_win_samples_1)))
       /(COUNT(wgts)-1) AS var
FROM i_partitions_train_win_samples_1
;

SELECT COUNT(*) FROM i_partitions_train_win_samples_2;

SELECT dx, COUNT(*) AS n
FROM i_partitions_train_win_samples_2
GROUP BY dx
ORDER BY n DESC
;


SELECT COUNT(*) FROM i_partitions_train_win_samples_3;

SELECT outcome, COUNT(*) AS n
FROM i_partitions_train_win_samples_3
GROUP BY outcome
ORDER BY n DESC
;

In [10]:
h.set_relcal()

SELECT min(i_st) AS i_st, max(i_et) AS i_et
FROM (
    SELECT i_id, i_st, i_et
	FROM samples_0
	UNION
		SELECT i_id, i_st, i_et
	FROM samples_1
	UNION
		SELECT i_id, i_st, i_et
	FROM samples_2
	UNION
		SELECT i_id, i_st, i_et
	FROM samples_3

);

INSERT  INTO i_relcal (i_id, i_st, i_et) VALUES (?, ?, ?);

In [11]:
h.fil_agg()

CREATE VIEW fil_characteristics_0 AS
    SELECT i_id,
	CASE
	    WHEN 25.52588664905965>age THEN 25.0
	    WHEN age>64.35706817998951 THEN 65.0 ELSE age
	END AS age,
	CASE
	    WHEN sex IN ('M') THEN 1
	    ELSE 0
	END AS sex,
	CASE
	    WHEN eth IN ('e0', 'e1', 'e2', 'e3', 'e4', 'e5') THEN eth
	    ELSE '_OTHER_'
	END AS eth,
	CASE
	    WHEN bin_ldc IN ('A', 'B') THEN bin_ldc
	    ELSE '_OTHER_'
	END AS bin_ldc,
	CASE
	    WHEN job IN ('j000', 'j001', 'j002', 'j003', 'j004', 'j005', 'j006', 'j007', 'j008', 'j009', 'j013', 'j010', 'j011', 'j014', 'j012', 'j016', 'j015', 'j018', 'j019', 'j017', 'j020', 'j022', 'j024', 'j026', 'j021', 'j025', 'j032', 'j023', 'j030', 'j027', 'j029', 'j050', 'j034', 'j036', 'j028', 'j031', 'j035', 'j054', 'j033', 'j037', 'j047', 'j049', 'j052', 'j038', 'j040', 'j046', 'j044', 'j039', 'j067', 'j075', 'j042', 'j051', 'j065', 'j077', 'j043', 'j066', 'j071', 'j045', 'j059', 'j064', 'j057', 'j091', 'j048', 'j068', 'j069', 'j074', 'j053', 'j060', 'j041', 'j061', 'j062', 'j081', 'j112', 'j063', 'j088', 'j089', 'j094', 'j055', 'j058', 'j076', 'j105', 'j056', 'j103', 'j116', 'j078', 'j084', 'j085', 'j087', 'j093', 'j106', 'j110', 'j124', 'j135', 'j210', 'j070', 'j080', 'j082', 'j086', 'j092', 'j096', 'j097', 'j113', 'j117', 'j120', 'j132', 'j079', 'j095', 'j102', 'j108', 'j129', 'j152', 'j162', 'j165', 'j170', 'j175', 'j177', 'j212', 'j261', 'j318', 'j359', 'j073', 'j099', 'j109', 'j114', 'j115', 'j121', 'j133', 'j136', 'j144', 'j147', 'j151', 'j159', 'j168', 'j176', 'j182', 'j189', 'j225', 'j233', 'j234', 'j240', 'j289', 'j072', 'j090', 'j104', 'j107', 'j118', 'j125', 'j145', 'j148', 'j149', 'j156', 'j160', 'j161', 'j166', 'j167', 'j192', 'j202', 'j244', 'j280', 'j284', 'j307', 'j614', 'j083', 'j098', 'j100', 'j111', 'j126', 'j128', 'j131', 'j139', 'j143', 'j146', 'j154', 'j158', 'j164', 'j172', 'j184', 'j186', 'j188', 'j190', 'j191', 'j193', 'j198', 'j217', 'j228', 'j238', 'j241', 'j248', 'j253', 'j262', 'j268', 'j321', 'j364', 'j374', 'j581', 'j101', 'j123', 'j137', 'j157', 'j163', 'j169', 'j173', 'j178', 'j187', 'j201', 'j213', 'j230', 'j231', 'j239', 'j251', 'j274', 'j279', 'j287', 'j291', 'j297', 'j299', 'j312', 'j339', 'j355', 'j361', 'j378', 'j398', 'j401', 'j405', 'j468', 'j469', 'j477', 'j803', 'j832', 'j119', 'j127', 'j141', 'j142', 'j150', 'j171', 'j180', 'j185', 'j194', 'j196', 'j199', 'j203', 'j206', 'j218', 'j219', 'j221', 'j222', 'j235', 'j237', 'j245', 'j249', 'j250', 'j255', 'j256', 'j260', 'j267', 'j270', 'j278', 'j282', 'j288', 'j294', 'j296', 'j303', 'j309', 'j311', 'j313', 'j323', 'j325', 'j326', 'j327', 'j334', 'j345', 'j348', 'j349', 'j368', 'j369', 'j382', 'j389', 'j393', 'j394', 'j397', 'j407', 'j409', 'j429', 'j434', 'j438', 'j449', 'j450', 'j482', 'j501', 'j520', 'j541', 'j560', 'j577', 'j625', 'j643', 'j646', 'j647', 'j666', 'j680', 'j683', 'j700', 'j746', 'j122', 'j130', 'j134', 'j140', 'j153', 'j155', 'j179', 'j181', 'j183', 'j195', 'j197', 'j200', 'j204', 'j205', 'j207', 'j208', 'j214', 'j215', 'j220', 'j227', 'j232', 'j257', 'j266', 'j269', 'j295', 'j298', 'j310', 'j316', 'j336', 'j337', 'j340', 'j344', 'j346', 'j352', 'j362', 'j365', 'j375', 'j391', 'j396', 'j404', 'j408', 'j425', 'j426', 'j435', 'j460', 'j471', 'j527', 'j533', 'j534', 'j543', 'j556', 'j561', 'j568', 'j583', 'j584', 'j585', 'j592', 'j603', 'j624', 'j649', 'j654', 'j655', 'j675', 'j679', 'j684', 'j687', 'j690', 'j702', 'j731', 'j783', 'j798', 'j804', 'j837', 'j882', 'j937', 'j209', 'j211', 'j216', 'j223', 'j226', 'j229', 'j243', 'j247', 'j254', 'j258', 'j264', 'j265', 'j271', 'j273', 'j276', 'j281', 'j285', 'j292', 'j293', 'j300', 'j302', 'j306', 'j308', 'j319', 'j320', 'j330', 'j331', 'j332', 'j333', 'j338', 'j341', 'j350', 'j351', 'j360', 'j363', 'j366', 'j372', 'j373', 'j379', 'j381', 'j384', 'j386', 'j388', 'j392', 'j399', 'j402', 'j416', 'j421', 'j427', 'j433', 'j441', 'j443', 'j447', 'j454', 'j456', 'j473', 'j474', 'j481', 'j485', 'j486', 'j494', 'j497', 'j498', 'j505', 'j506', 'j511', 'j512', 'j517', 'j518', 'j521', 'j523', 'j528', 'j535', 'j537', 'j551', 'j554', 'j567', 'j569', 'j574', 'j580', 'j587', 'j588', 'j591', 'j597', 'j599', 'j600', 'j602', 'j608', 'j612', 'j615', 'j637', 'j667', 'j670', 'j682', 'j693', 'j699', 'j711', 'j718', 'j738', 'j745', 'j752', 'j754', 'j757', 'j761', 'j772', 'j778', 'j779', 'j796', 'j817', 'j819', 'j823', 'j838', 'j839', 'j840', 'j842', 'j849', 'j853', 'j857', 'j869', 'j880', 'j903', 'j911', 'j919', 'j922', 'j941', 'j959', 'j974', 'j984', 'j997', 'j999', 'j138', 'j224', 'j236', 'j242', 'j246', 'j272', 'j283', 'j286', 'j290', 'j301', 'j304', 'j305', 'j317', 'j322', 'j324', 'j335', 'j342', 'j343', 'j353', 'j356', 'j357', 'j370', 'j371', 'j376', 'j385', 'j390', 'j400', 'j410', 'j412', 'j413', 'j418', 'j422', 'j428', 'j430', 'j436', 'j440', 'j442', 'j444', 'j445', 'j446', 'j448', 'j453', 'j455', 'j457', 'j459', 'j461', 'j465', 'j466', 'j472', 'j479', 'j480', 'j484', 'j487', 'j491', 'j493', 'j496', 'j500', 'j507', 'j509', 'j519', 'j526', 'j538', 'j539', 'j542', 'j545', 'j546', 'j549', 'j553', 'j555', 'j558', 'j562', 'j566', 'j570', 'j575', 'j576', 'j579', 'j582', 'j590', 'j595', 'j596', 'j604', 'j605', 'j618', 'j619') THEN job
	    ELSE '_OTHER_'
	END AS job
	FROM characteristics_0

;

CREATE VIEW ohe_characteristics_0 AS
    SELECT i_id,
	age,
	sex,
	CASE
	    WHEN eth IN ('e0') THEN 1
	    ELSE 0
	END AS eth_e0,
	CASE
	    WHEN eth IN ('e1') THEN 1
	    ELSE 0
	END AS eth_e1,
	CASE
	    WHEN eth IN ('e2') THEN 1
	    ELSE 0
	END AS eth_e2,
	CASE
	    WHEN eth IN ('e3') THEN 1
	    ELSE 0
	END AS eth_e3,
	CASE
	    WHEN eth IN ('e4') THEN 1
	    ELSE 0
	END AS eth_e4,
	CASE
	    WHEN eth IN ('e5') THEN 1
	    ELSE 0
	END AS eth_e5,
	CASE
	    WHEN eth IN ('_OTHER_') THEN 1
	    ELSE 0
	END AS eth__OTHER_,
	CASE
	    WHEN bin_ldc IN ('A') THEN 1
	    ELSE 0
	END AS bin_ldc_A,
	CASE
	    WHEN bin_ldc IN ('B') THEN 1
	    ELSE 0
	END AS bin_ldc_B,
	CASE
	    WHEN bin_ldc IN ('_OTHER_') THEN 1
	    ELSE 0
	END AS bin_ldc__OTHER_,
	job
	FROM fil_characteristics_0

;

CREATE VIEW fil_samples_0 AS
    SELECT i_id,
	i_st,
	i_et,
	CASE
	    WHEN 110.20257182128758>SBP THEN 110.0
	    WHEN SBP>129.7968201459127 THEN 130.0 ELSE SBP
	END AS SBP,
	CASE
	    WHEN 70.22000687502937>DBP THEN 70.0
	    WHEN DBP>89.83001698905726 THEN 90.0 ELSE DBP
	END AS DBP,
	CASE
	    WHEN type IN ('c0', 'c1', 'c2', 'c3', 'c4') THEN type
	    ELSE '_OTHER_'
	END AS type
	FROM win_samples_0

;

CREATE VIEW ohe_samples_0 AS
    SELECT i_id,
	i_st,
	i_et,
	SBP,
	DBP,
	CASE
	    WHEN type IN ('c0') THEN 1
	    ELSE 0
	END AS type_c0,
	CASE
	    WHEN type IN ('c1') THEN 1
	    ELSE 0
	END AS type_c1,
	CASE
	    WHEN type IN ('c2') THEN 1
	    ELSE 0
	END AS type_c2,
	CASE
	    WHEN type IN ('c3') THEN 1
	    ELSE 0
	END AS type_c3,
	CASE
	    WHEN type IN ('c4') THEN 1
	    ELSE 0
	END AS type_c4,
	CASE
	    WHEN type IN ('_OTHER_') THEN 1
	    ELSE 0
	END AS type__OTHER_
	FROM fil_samples_0

;

CREATE VIEW agg_samples_0 AS
    SELECT
	ohe_samples_0.i_id AS i_id,
	i_relcal.i_st AS i_st,
	i_relcal.i_et AS i_et,
	AVG(SBP) AS avg_SBP,
	MIN(SBP) AS min_SBP,
	MAX(SBP) AS max_SBP,
	AVG(DBP) AS avg_DBP,
	MIN(DBP) AS min_DBP,
	MAX(DBP) AS max_DBP,
	AVG(type_c0) AS avg_type_c0,
	AVG(type_c1) AS avg_type_c1,
	AVG(type_c2) AS avg_type_c2,
	AVG(type_c3) AS avg_type_c3,
	AVG(type_c4) AS avg_type_c4,
	AVG(type__OTHER_) AS avg_type__OTHER_,
	COUNT() as count
	FROM ohe_samples_0, i_relcal
	WHERE NOT (i_relcal.i_et < ohe_samples_0.i_st OR
	           i_relcal.i_st > ohe_samples_0.i_et)
	GROUP BY ohe_samples_0.i_id, i_relcal.i_st
;

CREATE VIEW fil_samples_1 AS
    SELECT i_id,
	i_st,
	i_et,
	CASE
	    WHEN 35.77526962531338>tmps THEN 35.0
	    WHEN tmps>37.50128558600996 THEN 38.0 ELSE tmps
	END AS tmps,
	CASE
	    WHEN 55.15220304016591>hrs THEN 55.0
	    WHEN hrs>74.83335382644515 THEN 75.0 ELSE hrs
	END AS hrs,
	CASE
	    WHEN 110.2210635783881>sbps THEN 110.0
	    WHEN sbps>129.737344231055 THEN 130.0 ELSE sbps
	END AS sbps,
	CASE
	    WHEN 25.09734881369824>rrs THEN 25.0
	    WHEN rrs>34.9078592778511 THEN 35.0 ELSE rrs
	END AS rrs,
	CASE
	    WHEN 70.18021638000687>dbps THEN 70.0
	    WHEN dbps>89.77256906181984 THEN 90.0 ELSE dbps
	END AS dbps,
	CASE
	    WHEN 94.67363176933745>sats THEN 94.0
	    WHEN sats>100.32748222645162 THEN 101.0 ELSE sats
	END AS sats,
	CASE
	    WHEN 105.81705326882766>wgts THEN 105.0
	    WHEN wgts>204.1761217662981 THEN 205.0 ELSE wgts
	END AS wgts
	FROM win_samples_1

;

CREATE VIEW ohe_samples_1 AS
    SELECT i_id,
	i_st,
	i_et,
	tmps,
	hrs,
	sbps,
	rrs,
	dbps,
	sats,
	wgts
	FROM fil_samples_1

;

CREATE VIEW agg_samples_1 AS
    SELECT
	ohe_samples_1.i_id AS i_id,
	i_relcal.i_st AS i_st,
	i_relcal.i_et AS i_et,
	AVG(tmps) AS avg_tmps,
	MIN(tmps) AS min_tmps,
	MAX(tmps) AS max_tmps,
	AVG(hrs) AS avg_hrs,
	MIN(hrs) AS min_hrs,
	MAX(hrs) AS max_hrs,
	AVG(sbps) AS avg_sbps,
	MIN(sbps) AS min_sbps,
	MAX(sbps) AS max_sbps,
	AVG(rrs) AS avg_rrs,
	MIN(rrs) AS min_rrs,
	MAX(rrs) AS max_rrs,
	AVG(dbps) AS avg_dbps,
	MIN(dbps) AS min_dbps,
	MAX(dbps) AS max_dbps,
	AVG(sats) AS avg_sats,
	MIN(sats) AS min_sats,
	MAX(sats) AS max_sats,
	AVG(wgts) AS avg_wgts,
	MIN(wgts) AS min_wgts,
	MAX(wgts) AS max_wgts,
	COUNT() as count
	FROM ohe_samples_1, i_relcal
	WHERE NOT (i_relcal.i_et < ohe_samples_1.i_st OR
	           i_relcal.i_st > ohe_samples_1.i_et)
	GROUP BY ohe_samples_1.i_id, i_relcal.i_st
;

CREATE VIEW fil_samples_2 AS
    SELECT i_id,
	i_st,
	i_et,
	CASE

In [12]:
h.create_partition_views_prior_to_normalization()

SELECT DISTINCT(partition) FROM i_partitions;

partitions: dev,train,test

CREATE VIEW i_partitions_dev_ohe_characteristics_0 AS
    SELECT * FROM ohe_characteristics_0
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='dev'
	)

;

CREATE VIEW i_partitions_train_ohe_characteristics_0 AS
    SELECT * FROM ohe_characteristics_0
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='train'
	)

;

CREATE VIEW i_partitions_test_ohe_characteristics_0 AS
    SELECT * FROM ohe_characteristics_0
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='test'
	)

;

CREATE VIEW i_partitions_dev_agg_samples_0 AS
    SELECT * FROM agg_samples_0
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='dev'
	)

;

CREATE VIEW i_partitions_train_agg_samples_0 AS
    SELECT * FROM agg_samples_0
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='train'
	)

;

CREATE VIEW i_partitions_test_agg_samples_0 AS
    SELECT * FROM agg_samples_0
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='test'
	)

;

CREATE VIEW i_partitions_dev_agg_samples_1 AS
    SELECT * FROM agg_samples_1
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='dev'
	)

;

CREATE VIEW i_partitions_train_agg_samples_1 AS
    SELECT * FROM agg_samples_1
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='train'
	)

;

CREATE VIEW i_partitions_test_agg_samples_1 AS
    SELECT * FROM agg_samples_1
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='test'
	)

;

CREATE VIEW i_partitions_dev_agg_samples_2 AS
    SELECT * FROM agg_samples_2
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='dev'
	)

;

CREATE VIEW i_partitions_train_agg_samples_2 AS
    SELECT * FROM agg_samples_2
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='train'
	)

;

CREATE VIEW i_partitions_test_agg_samples_2 AS
    SELECT * FROM agg_samples_2
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='test'
	)

;

CREATE VIEW i_partitions_dev_agg_samples_3 AS
    SELECT * FROM agg_samples_3
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='dev'
	)

;

CREATE VIEW i_partitions_train_agg_samples_3 AS
    SELECT * FROM agg_samples_3
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='train'
	)

;

CREATE VIEW i_partitions_test_agg_samples_3 AS
    SELECT * FROM agg_samples_3
	WHERE i_id IN (
	    SELECT i_id
	    FROM i_partitions
	    WHERE partition='test'
	)

;

In [13]:
%time h.fit_normalization(partition='train')

SELECT AVG(age),
COUNT(age)
FROM i_partitions_train_ohe_characteristics_0;

SELECT SUM((age-(44.94946343898178))*(age-(44.94946343898178)))/(8014-1)
FROM i_partitions_train_ohe_characteristics_0;

SELECT AVG(avg_SBP),
COUNT(avg_SBP),
AVG(min_SBP),
COUNT(min_SBP),
AVG(max_SBP),
COUNT(max_SBP),
AVG(avg_DBP),
COUNT(avg_DBP),
AVG(min_DBP),
COUNT(min_DBP),
AVG(max_DBP),
COUNT(max_DBP),
AVG(count),
COUNT(count)
FROM i_partitions_train_agg_samples_0;

SELECT SUM((avg_SBP-(120.00022821721213))*(avg_SBP-(120.00022821721213)))/(142613-1),
SUM((min_SBP-(117.52946910284355))*(min_SBP-(117.52946910284355)))/(142613-1),
SUM((max_SBP-(122.4674352972532))*(max_SBP-(122.4674352972532)))/(142613-1),
SUM((avg_DBP-(80.0199618641487))*(avg_DBP-(80.0199618641487)))/(142613-1),
SUM((min_DBP-(77.54534828819234))*(min_DBP-(77.54534828819234)))/(142613-1),
SUM((max_DBP-(82.49196450343375))*(max_DBP-(82.49196450343375)))/(142613-1),
SUM((count-(2.2197765982063347))*(count-(2.2197765982063347)))/(142613-1)
FROM i_partitions_train_agg_samples_0;

SELECT AVG(avg_tmps),
COUNT(avg_tmps),
AVG(min_tmps),
COUNT(min_tmps),
AVG(max_tmps),
COUNT(max_tmps),
AVG(avg_hrs),
COUNT(avg_hrs),
AVG(min_hrs),
COUNT(min_hrs),
AVG(max_hrs),
COUNT(max_hrs),
AVG(avg_sbps),
COUNT(avg_sbps),
AVG(min_sbps),
COUNT(min_sbps),
AVG(max_sbps),
COUNT(max_sbps),
AVG(avg_rrs),
COUNT(avg_rrs),
AVG(min_rrs),
COUNT(min_rrs),
AVG(max_rrs),
COUNT(max_rrs),
AVG(avg_dbps),
COUNT(avg_dbps),
AVG(min_dbps),
COUNT(min_dbps),
AVG(max_dbps),
COUNT(max_dbps),
AVG(avg_sats),
COUNT(avg_sats),
AVG(min_sats),
COUNT(min_sats),
AVG(max_sats),
COUNT(max_sats),
AVG(avg_wgts),
COUNT(avg_wgts),
AVG(min_wgts),
COUNT(min_wgts),
AVG(max_wgts),
COUNT(max_wgts),
AVG(count),
COUNT(count)
FROM i_partitions_train_agg_samples_1;

SELECT SUM((avg_tmps-(36.63207632117))*(avg_tmps-(36.63207632117)))/(142386-1),
SUM((min_tmps-(36.38495185791665))*(min_tmps-(36.38495185791665)))/(142386-1),
SUM((max_tmps-(36.87621006330754))*(max_tmps-(36.87621006330754)))/(142386-1),
SUM((avg_hrs-(64.99235111170972))*(avg_hrs-(64.99235111170972)))/(142386-1),
SUM((min_hrs-(62.5193304253183))*(min_hrs-(62.5193304253183)))/(142386-1),
SUM((max_hrs-(67.46353751460072))*(max_hrs-(67.46353751460072)))/(142386-1),
SUM((avg_sbps-(119.98982669030995))*(avg_sbps-(119.98982669030995)))/(142386-1),
SUM((min_sbps-(117.53253011039051))*(min_sbps-(117.53253011039051)))/(142386-1),
SUM((max_sbps-(122.44627599269153))*(max_sbps-(122.44627599269153)))/(142386-1),
SUM((avg_rrs-(30.00242274428394))*(avg_rrs-(30.00242274428394)))/(142386-1),
SUM((min_rrs-(28.772200182807364))*(min_rrs-(28.772200182807364)))/(142386-1),
SUM((max_rrs-(31.230210966747947))*(max_rrs-(31.230210966747947)))/(142386-1),
SUM((avg_dbps-(79.9663254775676))*(avg_dbps-(79.9663254775676)))/(142386-1),
SUM((min_dbps-(77.49351425680591))*(min_dbps-(77.49351425680591)))/(142386-1),
SUM((max_dbps-(82.43845326558771))*(max_dbps-(82.43845326558771)))/(142386-1),
SUM((avg_sats-(97.49760262690612))*(avg_sats-(97.49760262690612)))/(142386-1),
SUM((min_sats-(96.75225947422888))*(min_sats-(96.75225947422888)))/(142386-1),
SUM((max_sats-(98.24256521816345))*(max_sats-(98.24256521816345)))/(142386-1),
SUM((avg_wgts-(154.98448665999013))*(avg_wgts-(154.98448665999013)))/(142386-1),
SUM((min_wgts-(142.6101454760699))*(min_wgts-(142.6101454760699)))/(142386-1),
SUM((max_wgts-(167.39757468709897))*(max_wgts-(167.39757468709897)))/(142386-1),
SUM((count-(2.2223954602278315))*(count-(2.2223954602278315)))/(142386-1)
FROM i_partitions_train_agg_samples_1;

SELECT AVG(count),
COUNT(count)
FROM i_partitions_train_agg_samples_2;

SELECT SUM((count-(2.218576515448887))*(count-(2.218576515448887)))/(142664-1)
FROM i_partitions_train_agg_samples_2;

SELECT AVG(count),
COUNT(count)
FROM i_partitions_train_agg_samples_3;

SELECT SUM((count-(1.0))*(count-(1.0)))/(55997-1)
FROM i_partitions_train_agg_samples_3;

CPU times: user 21.5 s, sys: 184 ms, total: 21.6 s
Wall time: 21.6 s

In [ ]:
%time h.fit_normalization(partition='train', via_sql_qds=False)

In [14]:
h.normalize()

CREATE VIEW nrm_characteristics_0 AS
    SELECT i_id,
	(age-44.94946343898178)/9.596336325464671 as age,
	sex,
	eth_e0,
	eth_e1,
	eth_e2,
	eth_e3,
	eth_e4,
	eth_e5,
	eth__OTHER_,
	bin_ldc_A,
	bin_ldc_B,
	bin_ldc__OTHER_,
	job
	FROM ohe_characteristics_0

;

CREATE VIEW nrm_samples_0 AS
    SELECT i_id,
	i_st,
	i_et,
	(avg_SBP-120.00022821721213)/3.6969963874843086 as avg_SBP,
	(min_SBP-117.52946910284355)/4.488291898422897 as min_SBP,
	(max_SBP-122.4674352972532)/4.486789225940701 as max_SBP,
	(avg_DBP-80.0199618641487)/3.695838865111813 as avg_DBP,
	(min_DBP-77.54534828819234)/4.487669858678003 as min_DBP,
	(max_DBP-82.49196450343375)/4.485413699544264 as max_DBP,
	avg_type_c0,
	avg_type_c1,
	avg_type_c2,
	avg_type_c3,
	avg_type_c4,
	avg_type__OTHER_,
	(count-2.2197765982063347)/1.1749786640778028 as count
	FROM agg_samples_0

;

CREATE VIEW nrm_samples_1 AS
    SELECT i_id,
	i_st,
	i_et,
	(avg_tmps-36.63207632117)/0.39027435090847523 as avg_tmps,
	(min_tmps-36.38495185791665)/0.5036545013894659 as min_tmps,
	(max_tmps-36.87621006330754)/0.4729610424861321 as max_tmps,
	(avg_hrs-64.99235111170972)/3.7097201386489957 as avg_hrs,
	(min_hrs-62.5193304253183)/4.504764962835912 as min_hrs,
	(max_hrs-67.46353751460072)/4.502949155394478 as max_hrs,
	(avg_sbps-119.98982669030995)/3.68177814323896 as avg_sbps,
	(min_sbps-117.53253011039051)/4.478810712946643 as min_sbps,
	(max_sbps-122.44627599269153)/4.466147097520394 as max_sbps,
	(avg_rrs-30.00242274428394)/1.8595197746116736 as avg_rrs,
	(min_rrs-28.772200182807364)/2.2527922424025713 as min_rrs,
	(max_rrs-31.230210966747947)/2.2528593793064142 as max_rrs,
	(avg_dbps-79.9663254775676)/3.6907218412565097 as avg_dbps,
	(min_dbps-77.49351425680591)/4.484218684097984 as min_dbps,
	(max_dbps-82.43845326558771)/4.491873788924563 as max_dbps,
	(avg_sats-97.49760262690612)/1.1134334454208612 as avg_sats,
	(min_sats-96.75225947422888)/1.320637803808841 as min_sats,
	(max_sats-98.24256521816345)/1.3255410941305086 as max_sats,
	(avg_wgts-154.98448665999013)/18.512759866778023 as avg_wgts,
	(min_wgts-142.6101454760699)/22.478246168586015 as min_wgts,
	(max_wgts-167.39757468709897)/22.507192755900476 as max_wgts,
	(count-2.2223954602278315)/1.1842620328857494 as count
	FROM agg_samples_1

;

CREATE VIEW nrm_samples_2 AS
    SELECT i_id,
	i_st,
	i_et,
	concat_dx,
	(count-2.218576515448887)/1.1757365870569858 as count
	FROM agg_samples_2

;

CREATE VIEW nrm_samples_3 AS
    SELECT i_id,
	i_st,
	i_et,
	avg_outcome,
	(count-1.0)/0.0 as count
	FROM agg_samples_3

;

In [15]:
h.execute("PRAGMA table_info(fil_characteristics_0);", size=10)

PRAGMA table_info(fil_characteristics_0);
(0, 'i_id', 'TEXT', 0, None, 0)
(1, 'age', '', 0, None, 0)
(2, 'sex', '', 0, None, 0)
(3, 'eth', '', 0, None, 0)
(4, 'bin_ldc', '', 0, None, 0)
(5, 'job', '', 0, None, 0)

In [16]:
#SELECT * FROM nrm_samples_3 WHERE i_id=='00000';
#SELECT * FROM agg_samples_3 WHERE i_id=='00000';
#SELECT * FROM ohe_samples_3 WHERE i_id=='00000';

In [17]:
#SELECT * FROM agg_samples_0 LIMIT 10;
#CREATE INDEX samples_0_index_type ON samples_0(type);
#SELECT * FROM i_partitions_dev_ohe_characteristics_0;
#["SBP", "DBP", "type"]

In [18]:
#h.interactive_session()